server:
  port: 20001

spring:
  application:
    name: Client Demo
  jackson:
    serialization:
      write-dates-as-timestamps: false



  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    url: ${DATBASE_URL:jdbc:postgresql://localhost/client-demo-liq}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/liquibase-changelog.xml